Added azure kms support
jku/repository-playground pull request #89
Opened 2023-05-26 11:20 UTC by kommendorkapten

2023-05-26 13:59 UTC, jku commented
This doesn't work as it is as the GCP input is just the KMS key id, not the fully formed URI: the idea is that user input is something they can just copy-paste from GCP KMS UI. User does not need to form the URI, the `GCPSigner.import_()` method does that.

The AzureSigner.import_() arguments can be whatever you want,but I don't know why you would want to make your users build the full URI? Why not let AzureSigner build the URI from some logical values that the user understands (like keyid and vaultname)?

I think now that we have mutliple different keys, we want to modify the UI so it first asks which keytype we want to use
```
Choose online key:
1. Sigstore
2. Google Cloud KMS
3. Azure KMS
```

Feel free to choose how you want to enter the azure details but it sounds like something like this would make sense:  
```
Please enter vault name: 
Please enter key name:
```

2023-05-30 07:10 UTC, kommendorkapten commented
Do not merge bore:
https://github.com/secure-systems-lab/securesystemslib/pull/588
https://github.com/malancas/securesystemslib/pull/8

2023-05-30 13:59 UTC, kommendorkapten commented
Tests are failing as the AzureSigner does not exist in securesystemslib. It works locally so when the pr against securesystemslib is merged I'll rerun the tests.

2023-06-01 16:16 UTC, jku commented on playground/signer/playground_sign/delegate.py
> +            show_default=False,
What do you think about defaulting to sigstore (and not hiding the default)? 

I'm a bit conflicted:
* it's pretty clear the sigstore support is a little experimental still, but...
* mostly for demonstration purposes I'd like to have default values that (once the current dependency fiasco is solved) just work if you keep pressing enter

2023-06-02 05:57 UTC, kommendorkapten commented on playground/signer/playground_sign/delegate.py
> +            show_default=False,
Yes, I agree. Default to sigstore makes sense as that would make it easy to get on board. I'll update. I think for a real situation, when you are actually configuring a trust root, you don't blindly press enter, you think carefully about your config so there is no need to rely on the default values.

2023-06-02 05:59 UTC, kommendorkapten commented on playground/signer/playground_sign/delegate.py
> +            show_default=False,
Also one thing I would like to have feedback on. The local testing key, before it was based on a "known value", not it's a "hidden option" (4). You are ok with that?

2023-06-02 07:00 UTC, jku commented on playground/signer/playground_sign/delegate.py
> +            show_default=False,
LGTM

2023-06-02 07:01 UTC, jku commented on playground/signer/playground_sign/delegate.py
> +            show_default=False,
hiding option 4 seems good to me

2023-06-02 07:07 UTC, jku requested changes
looks good to me, apart from the default online key change

2023-06-02 07:07 UTC, jku commented on playground/tests/e2e.sh
> +        "4"                 # Enter key id
nit pick: this would make it easier to find the right place in the code
```suggestion
        "4"                 # Select online keytype
```

same nit applies to two other locations

2023-06-02 07:07 UTC, jku commented on playground/signer/playground_sign/delegate.py
> +        )
we want default = 1 and range = 1-4 I guess

2023-06-02 10:39 UTC, jku approved these changes

2023-06-02 10:39 UTC, merged